<?php

/**
 * @file
 * Global attachments for the Budget module.
 */

use Drupal\Core\Render\AttachmentsResponseProcessorInterface;
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_page_attachments().
 */
function budget_page_attachments(array &$attachments) {
  // Подключаем библиотеку ко всем страницам.
  $attachments['#attached']['library'][] = 'budget/global_assets';
}

/**
 * Implements hook_theme().
 */

function budget_theme($existing, $type, $theme, $path) {
  return [
    'budget_bl' => [
      'variables' => ['data' => []],
      'template' => 'budget-bl', // Имя файла шаблона без расширения.
    ],
    'budget_bl_main' => [
      'variables' => ['data' => []],
      'template' => 'budget-bl_main',
    ],
    'budget_execut_bl' => [
      'variables' => ['data' => []],
      'template' => 'budget-execut-bl',
    ],
    'budget_execut_bl_main' => [
      'variables' => ['data' => []],
      'template' => 'budget-execut-bl_main',
    ],
  ];
}

function budget_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];

  switch ($key) {
    case 'feedback_message':
      // Формируем тему письма
      $message['subject'] = t('Новое сообщение из формы обратной связи', [], $options);

      // Формируем тело письма (массив строк)
      $message['body'][] = t('Здравствуйте!', [], $options);
      $message['body'][] = '';
      $message['body'][] = t('На сайте было отправлено новое сообщение:', [], $options);
      $message['body'][] = '';

      // Добавляем данные из формы
      foreach ($params['form_data'] as $field_name => $field_value) {
        $message['body'][] = t('@field: @value', [
          '@field' => $field_name,
          '@value' => $field_value,
        ], $options);
      }

      $message['body'][] = '';
      $message['body'][] = t('С уважением, автоматическая система сайта', [], $options);
      break;
  }
}
