<?php

/**
 * @file
 * Global attachments for the Budget module.
 */

use Drupal\Core\Render\AttachmentsResponseProcessorInterface;

/**
 * Implements hook_page_attachments().
 */
function budget_page_attachments(array &$attachments) {
  // Подключаем библиотеку ко всем страницам.
  $attachments['#attached']['library'][] = 'budget/global_assets';
}

/**
 * Implements hook_theme().
 */
/*function budget_theme($existing, $type, $theme, $path) {
  return [
    'budget_incomes_page' => [
      'variables' => ['income_data' => NULL],
      'template' => 'budget-incomes-page', // пробовали ставить html целиком
    ],
  ];
}*/
function budget_theme($existing, $type, $theme, $path) {
  return [
    'budget_bl' => [
      'variables' => ['data' => []],
      'template' => 'budget-bl', // Имя файла шаблона без расширения.
    ],
  ];
}
