<?php

/**
 * @file
 * Основной файл модуля Graph Project.
 */
function graph_project_theme($existing, $type, $theme, $path) {
  return [
    'graph_project_page' => [
      'variables' => [
        'items' => [],
        'year' => '',
        'plan_years' => '',
        'file_url' => '',
        'file_name' => '',
      ],
      'template' => 'graph-project-page', // имя файла без .html.twig
    ],
  ];
}
