<?php

/**
 * Implements hook_theme().
 */
function norm_docs_theme($existing, $type, $theme, $path) {
  return [
    'normative_documents_page' => [
      'variables' => [
        'documents_by_category' => [],
        'page_title' => '',
      ],
      'template' => 'normative-documents-page',
      'path' => $path . '/templates',
    ],
    'budget_documents_page' => [
      'variables' => [
        'documents_by_category' => [],
        'page_title' => '',
      ],
      'template' => 'budget-documents-page',
      'path' => $path . '/templates',
    ],
  ];
}
