<?php

function budget_theme_preprocess_block(&$variables) {
  // Проверяем, что это блок меню
  if ($variables['plugin_id'] == 'system_menu_block:main') {
    // Получаем ID блока
    $block_id = $variables['elements']['#id'] ?? '';

    // Добавляем класс с ID блока к меню
    $variables['content']['#attributes']['class'][] = 'menu-block-' . str_replace('-', '_', $block_id);

    // Debug
    //\Drupal::messenger()->addMessage('Block ID: ' . $block_id);
    //\Drupal::messenger()->addMessage('Plugin ID: ' . $variables['plugin_id']);

    if (isset($variables['content']['#items'])) {
      $variables['content']['#attributes']['data-block-id'] = $block_id;
    }
  }

  if (isset($variables['content']['#block_content'])) {
    $block_content = $variables['content']['#block_content'];

    if ($block_content->bundle() == 'main_links') { // машинное имя типа блока "полезные ссылки"
      // Добавляем контекстуальные ссылки
      $variables['elements']['#contextual_links'] = [
        'block' => [
          'route_parameters' => ['block' => $block_content->id()],
        ],
      ];
    }
  }

}

function budget_theme_preprocess_page(&$variables) {
  // Добавляем переменную 'donor_news' для использования в page.html.twig
  $variables['donor_news'] = mynews_display_news_block();
}
