<?php


/**
 * @file
 * Global attachments for the Budget module.
 */

use Drupal\Core\Render\AttachmentsResponseProcessorInterface;


/**
 * Implements hook_theme().
 */
function budget_execution_theme($existing, $type, $theme, $path) {

  //\Drupal::logger('budget_execution')->debug('hook_theme called');

  return [
    'budget_execution_dynamic_indicators' => [
      'variables' => ['data' => []],
      'template' => 'budget-execution-dynamic-indicators',
      'render element' => 'elements',
    ],
    'budget_execution_list' => [
      'variables' => [
        'items' => [],
        'pager' => NULL,
        'filter_form' => NULL,
      ],
      'template' => 'budget-execution-list',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function budget_execution_preprocess_page(&$variables) {
  // Добавляем библиотеку на страницу со списком сущностей
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name === 'entity.budget_execution.collection') {
    $variables['#attached']['library'][] = 'budget_execution/budget-execution-list';
  }
}

function budget_execution_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  if ($route_name == 'entity.budget_execution.collection') {
    return [
      '#type' => 'link',
      '#title' => 'Импорт данных из XLSX-файла',
      '#url' => \Drupal\Core\Url::fromRoute('entity.budget_execution.import_form'),
      '#attributes' => ['class' => ['button', 'button--primary']],
    ];
  }
}

